<div class="container">
   <nav class="woocommerce-breadcrumb">
      <ul>
            <li><a href="https://sorvetedecerveja.com.br">Início</a></li>
            <li><a href="detalhe/?detalhe_anunciante=<?php echo $users[0]->ID; ?>">Detalhe</a></li>
            <li><?php echo $users[0]->nome_do_seu_negocio; ?></li>
      </ul>
   </nav>

   <div id="primary" class="content-area">
      <main id="main" class="site-main" role="main">
       
         <div class="woocommerce-notices-wrapper"></div>
        
         <div id="product-2887" class="single-product product type-product post-2887 status-publish first instock product_cat-auto-escola product_cat-automotivo product_cat-toys-video-games product_cat-cosmeticos product_cat-eletronicos product_cat-imobiliarias product_cat-lavanderias product_cat-moda-accessorios product_cat-sorveterias has-post-thumbnail shipping-taxable product-type-simple">
            <div class="single-product-wrapper style-1">

            <div class="column single-product-detail">
                  <div class="product-detail-inner">
                  <div class="woocommerce-product-details__short-description linha_divisoria_detalhe">
                     <span class='endereco_detalhe_titulo'>Endereço:</span>
                        <p><i class="klb-icon-home"></i> <?php echo $users[0]->endereco; ?>, <?php echo $users[0]->numero; ?> - <?php echo $users[0]->cidade; ?>,<?php echo $users[0]->estado; ?> - <?php echo $users[0]->cep; ?></p>
                     </div>

                     <?php if(isset($users[0]->telefone)){  ?>
                        <div class='linha_divisoria_detalhe'>
                              <h1 class="product_title entry-title telefone_detalhe_anuncio "><i class="klb-icon-phone"></i><?php echo $users[0]->telefone; ?></h1>
                        </div> 
                        <?php  }  ?>
                      <?php if(isset($users[0]->whatsapp)){  ?>
                        <div class='linha_divisoria_detalhe'>
                            <div class="whatsapp_icon_search  whats_icone_detalhe primary "><a target='_blank' href='https://wa.me/<?php echo preg_replace("/[^0-9]/", "", $users[0]->whatsapp);  ?>?text=%F0%9F%91%8B%20Ol%C3%A1!%20Obrigado%20por%20entrar%20em%20contato.%20Como%20posso%20ajudar%20voc%C3%AA%20hoje%3F'><div class="whatsapp_icon_resultado_detalhe"></div></a></div>
                            <h1 class="product_title entry-title telefone_detalhe_anuncio"><?php echo $users[0]->whatsapp; ?></h1>
                        </div> 
                      <?php  }  ?>
                   
                  
                     <?php if(isset($users[0]->website)){  ?>
                        <div class='linha_divisoria_detalhe site_linha_detalhe'>
                           <div class="woocommerce-product-details__short-description">
                              <p><a href='https://<?php echo $users[0]->website; ?>'><i class="klb-icon-www"></i><?php echo $users[0]->website; ?></a></p>
                           </div>
                        </div>
                     <?php } ?>
                     <div class='linha_divisoria_detalhe'>
                     <div class="product-share social-container">
                        <span>Redes Sociais:</span>
                        <div class="site-social lista_rede_social">
                           <ul class="color-social rede_social_padding">
                              <?php if(isset($users[0]->endereco_facebook)){  ?>
                               <li><a href="<?php echo $users[0]->endereco_facebook; ?>" class="filled social-color facebook" target="_blank"><i class="klb-social-icon-facebook"></i></a></li>
                              <?php } ?>
                              <?php if(isset($users[0]->endereco_instagram)){  ?>
                               <li><a href="<?php echo $users[0]->endereco_instagram; ?>" class="filled social-color instagram" target="_blank"><i class="klb-social-icon-instagram"></i></a></li>
                              <?php } ?>
                              <?php if(isset($users[0]->endereco_linkedin)){  ?>
                               <li><a href="<?php echo $users[0]->endereco_linkedin; ?>" class="filled social-color linkedin" target="_blank"><i class="klb-social-icon-linkedin"></i></a></li>
                              <?php } ?>

                           </ul>
                        </div>
                        <!-- site-social -->
                     </div>
                     </div>
                     <br>
                     <?php if(isset($users[0]->segunda_horario_inicio) and isset($users[0]->segunda_horario_fim) ){  ?>
                     <div class='linha_divisoria_detalhe'>
                     <div class="product-share social-container">
                        <span>Horário de Funcionamento:</span>
                        <div class="site-social">
                           <ul class="color-social detalhes_horario_funcionanemto">
                              <?php if(isset($users[0]->segunda_horario_inicio) and isset($users[0]->segunda_horario_fim) ){  ?>
                               <li>Segunda - <?php echo $users[0]->segunda_horario_inicio; ?>:<?php echo $users[0]->segunda_horario_fim; ?> </li>
                              <?php } ?>
                              <?php if(isset($users[0]->terca_horario_inicio) and isset($users[0]->terca_horario_fim) ){  ?>
                               <li>Terça - <?php echo $users[0]->terca_horario_inicio; ?>:<?php echo $users[0]->terca_horario_fim; ?> </li>
                              <?php } ?>
                              <?php if(isset($users[0]->quarta_horario_inicio) and isset($users[0]->quarta_horario_fim) ){  ?>
                               <li>Quarta - <?php echo $users[0]->quarta_horario_inicio; ?>:<?php echo $users[0]->quarta_horario_fim; ?> </li>
                              <?php } ?>
                              <?php if(isset($users[0]->quinta_horario_inicio) and isset($users[0]->quinta_horario_fim) ){  ?>
                               <li>Quinta - <?php echo $users[0]->quinta_horario_inicio; ?>:<?php echo $users[0]->quinta_horario_fim; ?> </li>
                              <?php } ?>
                              <?php if(isset($users[0]->sexta_horario_inicio) and isset($users[0]->sexta_horario_fim) ){  ?>
                               <li>Sexta - <?php echo $users[0]->sexta_horario_inicio; ?>:<?php echo $users[0]->sexta_horario_fim; ?> </li>
                              <?php } ?>
                              <?php if(isset($users[0]->sabado_horario_inicio) and isset($users[0]->sabado_horario_fim) ){  ?>
                               <li>Sábado - <?php echo $users[0]->sabado_horario_inicio; ?>:<?php echo $users[0]->sabado_horario_fim; ?> </li>
                              <?php } ?>
                              <?php if(isset($users[0]->domingo_horario_inicio) and isset($users[0]->domingo_horario_fim) ){  ?>
                               <li>Domingo - <?php echo $users[0]->domingo_horario_inicio; ?>:<?php echo $users[0]->domingo_horario_fim; ?> </li>
                              <?php } ?>
                           </ul>
                        </div>
                        <!-- site-social -->
                     </div>
                     </div>
                  <?php } ?>
                     <!-- product-share -->		
                     <!-- product-share -->			
                  </div>
               </div>


               <div class="column single-product-gallery ">
                  <div class="woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-8 images" data-columns="8" style="opacity: 1; transition: opacity 0.25s ease-in-out;">
                     <div class="woocommerce-product-gallery__wrapper">
                        <div class="woocommerce-product-gallery__image" style="position: relative; overflow: hidden;">
                        <a href="#">
                        <img width="600" height="338" src="<?php echo $users[0]->foto_do_anunciante; ?>" class="wp-post-image" alt="" title="jaragua"
                         data-large_image_width="984" data-large_image_height="554" decoding="async" ></a>
                         <img alt="" src="<?php echo $users[0]->foto_do_anunciante; ?>" class="zoomImg" style="position: absolute; top: -0.481929px; left: -558.986px; opacity: 0; width: 984px; height: 554px; border: none; max-width: none; max-height: none;" aria-hidden="true"></div>
                     </div>
                  </div>

                  <div class="product-detail-inner">
                     <div class="product-category">
                        <a href="#"><?php echo $users[0]->categoria; ?></a></div>
                     <h1 class="product_title entry-title"><?php echo $users[0]->nome_do_seu_negocio; ?></h1>
                     <div class="product-meta">
                     </div>
                     <div class="woocommerce-product-details__short-description">
                        <p><?php echo $users[0]->descricao; ?></p>
                     </div>		

                     
                  </div>
               </div>
          
               
            </div>
            <div class="single-product-tabs-wrapper style-1 anuncios_semelhantes_bloco">
                              

               <?php if(count($users_anunciantes_semelhantes)>0){ ?> 
               <section class="site-module klb-module related" id="related-products">
                  <div class="klb-module-header d-flex align-items-center flex-wrap mb-30 gap-2 gap-md-4">
                     <div class="column">
                        <h3 class="entry-title">Anúncios Semelhantes</h3>
                     </div>
                     <!-- column -->
                  </div>
                  <!-- site-module-header -->
                  <div class="site-module-body">
                     <div class="shop-products-wrapper">
                        <div class="products product-grid-style grid-column-2-mobile grid-column-6 grid-gap-30">
                        <?php  foreach($users_anunciantes_semelhantes as $dadosAnunciantes){ 
                           
                              if(trim($dadosAnunciantes->foto_do_anunciante)==''){
                                $dadosAnunciantes->foto_do_anunciante = 'https://2.gravatar.com/avatar/ec65a0d5f2c7d6732407df4c552409c9?s=64&d=mm&r=g';
                              }else{
                                $upload_url = wp_upload_dir();
                                $upload_url = $upload_url['baseurl'] . '/addify_registration_uploads/';
                                $dadosAnunciantes->foto_do_anunciante = $upload_url.$dadosAnunciantes->foto_do_anunciante;
                              }
                            
                           
                           ?>

                           <div class="product type-product post-2885 status-publish instock product_cat-cosmeticos has-post-thumbnail shipping-taxable product-type-simple">
                              <div class="product-wrapper with-content-fade product-type-1 product-type-4">
                                 <div class="product-inner">
                                    <div class="product-thumbnail-wrapper">
                                      
                                       <!-- product-buttons -->
                                       <div class="product-thumbnail thumbnail-gallery-dots-style-1 thumbnail-gallery-hover">
                                       <a href="/detalhe?detalhe_anunciante=<?php echo $dadosAnunciantes->ID; ?>">
                                          <img width="650" height="354" src="<?php echo $dadosAnunciantes->foto_do_anunciante; ?>"
                                           class="attachment-1000x1000 size-1000x1000" alt="" decoding="async" ></a></div>
                                       <!-- product-thumbnail -->
                                    </div>
                                    <!-- product-thumbnail-wrapper -->
                                    <div class="product-content-wrapper">
                                       <div class="product-content-body">
                                          <div class="product-content-row">
                                             <div class="product-brand"><a href="#" rel="tag"><?php echo $dadosAnunciantes->categoria; ?></a></div>
                                             <!-- product-brand -->
                                             <h2 class="product-title"><a href="#"><span><?php echo $dadosAnunciantes->nome_do_seu_negocio; ?></span></a></h2>
                                          </div>
                                          <!-- product-content-row -->
                                          <div class="product-content-row">
                                             <div class="product-price-wrapper"><span class="price"></span></div>
                                             <!-- product-price-wrapper -->
                                          </div>
                                          <!-- product-content-row -->
                                       </div>
                                       <!-- product-content-body -->
                                       <div class="product-content-footer"><?php echo $dadosAnunciantes->descricao; ?></div>
                                       <!-- product-content-footer -->
                                    </div>
                                    <!-- product-content-wrapper -->
                                 </div>
                                 <!-- product-inner -->
                                
                                 <!-- product-hidden-content -->
                              </div>
                              <!-- product-wrapper -->
                              <div class="product-content-fade style-3" style="margin-bottom: -16px;"></div>
                           </div>
                           <?php } ?>
                        </div>
                     </div>
                  </div>
               </section>
               <?php } ?>
            </div>
         </div>
      </main>
   </div>
</div>