            <section class="space min gray">
                  <div class="container">
                  
                     <div class="row justify-content-center">
                        <div class="col-xl-5 col-lg-7 col-md-9 col-sm-12">
                           <div class="sec_title position-relative text-center mb-5">
                              <h6 class="theme-cl mb-0">Anúncie Conosco</h6>
                              <h2 class="ft-bold">Escolha o pacote</h2>
                           </div>
                        </div>
                     </div>
                     
                     <div class="row">
                     
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
                           <div class="Goodup-price-wrap">
                              <div class="Goodup-author-header">
                                 <div class="Goodup-price-currency">
                                    <h3><span class="Goodup-new-price">R$<del>9,90</del></span><span class="Goodup-old-price">R$<del>13,90</del></span></h3>
                                 </div>
                                 <div class="Goodup-price-title">
                                    <div class="Goodup-price-tlt"><h4>Mensal</h4></div><div class="Goodup-price-ribbon"><span class="Goodup-ribbon-offer all">35% Off</span></div>
                                 </div>
                                 <div class="Goodup-price-subtitle">Melhor escolha pra pequenos comércios</div>
                              </div>
                              <div class="Goodup-price-body">
                                 <ul class="price__features">
                                    <li><i class="klb-icon-chevron-right"></i>Anúnicos na home do site</li>
                                    <li><i class="klb-icon-chevron-right"></i>Destaque na busca de anúnciantes</li>
                                    <li><i class="klb-icon-chevron-right"></i>Acesso ao relatório de acessos</li>
                                    <li><i class="klb-icon-chevron-right"></i>Recebecimento de novidades do site</li>
                                  
                                 </ul>
                              </div>
                              <div class="Goodup-price-bottom">
                                 <a class="Goodup-price-btn active" target='_new' href="/checkout_plano?plano=plano_mensal"><i class="klb-icon-shopping-bag"></i> Anúncie Agora</a>
                              </div>
                           </div>
                        </div>
                        
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
                           <div class="Goodup-price-wrap">
                              <div class="Goodup-author-header">
                                 <div class="Goodup-price-currency">
                                    <h3><span class="Goodup-new-price theme-cl">R$<del>49,90</del></span><span class="Goodup-old-price">R$<del>59,40</del></span></h3>
                                 </div>
                                 <div class="Goodup-price-title">
                                    <div class="Goodup-price-tlt"><h4>Semestral</h4></div><div class="Goodup-price-ribbon"><span class="Goodup-ribbon-offer">20% Off</span></div>
                                 </div>
                                 <div class="Goodup-price-subtitle">Melhor escolha para comércios médios </div>
                              </div>
                              <div class="Goodup-price-body">
                                 <ul class="price__features">
                                     <li><i class="klb-icon-chevron-right"></i>Anúnicos na home do site</li>
                                    <li><i class="klb-icon-chevron-right"></i>Destaque na busca de anúnciantes</li>
                                    <li><i class="klb-icon-chevron-right"></i>Acesso ao relatório de acessos</li>
                                    <li><i class="klb-icon-chevron-right"></i>Recebecimento de novidades do site</li>
                                 </ul>
                              </div>
                              <div class="Goodup-price-bottom">
                                 <a class="Goodup-price-btn active" target='_new' href="/checkout_plano?plano=plano_semenstral"><i class="klb-icon-shopping-bag"></i>Anúncie Agora</a>
                              </div>
                           </div>
                        </div>
                        
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
                           <div class="Goodup-price-wrap">
                              <div class="Goodup-author-header">
                                 <div class="Goodup-price-currency">
                                    <h3><span class="Goodup-new-price">R$<del>79,90</del></span><span class="Goodup-old-price">R$<del>118,80</del></span></h3>
                                 </div>
                                 <div class="Goodup-price-title">
                                    <div class="Goodup-price-tlt"><h4>Anual</h4></div><div class="Goodup-price-ribbon"><span class="Goodup-ribbon-offer all">40% Off</span></div>
                                 </div>
                                 <div class="Goodup-price-subtitle">Melhor escolha para grandes comércios</div>
                              </div>
                              <div class="Goodup-price-body">
                                 <ul class="price__features">
                                    <li><i class="klb-icon-chevron-right"></i>Anúnicos na home do site</li>
                                    <li><i class="klb-icon-chevron-right"></i>Destaque na busca de anúnciantes</li>
                                    <li><i class="klb-icon-chevron-right"></i>Acesso ao relatório de acessos</li>
                                    <li><i class="klb-icon-chevron-right"></i>Recebecimento de novidades do site</li>
                                 </ul>
                              </div>
                              <div class="Goodup-price-bottom">
                                 <a class="Goodup-price-btn active" target='_new' href="</checkout_plano?plano=plano_anual"><i class="klb-icon-shopping-bag"></i>Anúncie Agora</a>
                              </div>
                           </div>
                        </div>
                        
                     </div>
                     
                  </div>
               </section>