





<div class="elementor-element elementor-element-b16ad1f e-flex e-con-boxed e-con e-parent e-lazyloaded" data-id="b16ad1f" data-element_type="container">
   <div class="e-con-inner">
      <div class="elementor-element elementor-element-d50318c e-con-full e-flex e-con e-child" data-id="d50318c" data-element_type="container">
         <div class="elementor-element elementor-element-2d49846 elementor-widget elementor-widget-bevesi-product-categories" data-id="2d49846" data-element_type="widget" data-widget_type="bevesi-product-categories.default">
            <div class="elementor-widget-container">

                  <div class="site-slider-categorias">
                   
                     <!-- slider-item --><!-- slider-item --><!-- slider-item --><!-- slider-item --><!-- slider-item --><!-- slider-item --><!-- slider-item --><!-- slider-item --><!-- slider-item -->
                   
                     <?php
                           $contador= 0;
                           foreach($users_anunciantes_Categoria as $dadosCategoria){ 

                           $contador++; ?>   
                        <div >
                      
                        
                           <div  role="tabpanel">
                              <div class="site-category-box style-2">
                                 <div class="site-category-thumbnail">
                                    <a href="/s=?categoria_principal=<?php echo $dadosCategoria->id_categoria_principal ?>" tabindex="0">
                                    <img src="<?php echo '/wp-content/themes/bevesi/assets/img/imagens_categorias/'.$dadosCategoria->id_categoria_principal.'.png'; ?>" />
                                    </a></div>
                                 <!-- site-category-thumbnail -->
                                 <div class="site-category-content">
                                    <h4 class="category-name"><a href="/s=?categoria=<?php echo $dadosCategoria->nome ?>" tabindex="0"><?php echo $dadosCategoria->nome ?></a></h4>
                                 </div>
                                 <!-- site-category-content -->
                              </div>
                              <!-- site-category-box -->
                           </div>
                           
                       
                        </div>
                        <?php } ?>
                           
                        
                 
                  <!-- site-slider -->
               </div>
               <!-- site-slider-wrapper -->		
               
            </div>
         </div>
      </div>
   </div>
</div>
