

<div class="e-con-inner carrosel_anunciantes_home <?php echo  $classe_carrosel; ?> ">
   <div class="elementor-element elementor-element-ae0b646 elementor-widget__width-inherit elementor-widget elementor-widget-bevesi-product-tab-carousel" data-id="ae0b646" data-element_type="widget" data-widget_type="bevesi-product-tab-carousel.default">
      <div class="elementor-widget-container">
         <div class="klb-module">
            <div class="site-module-header style-1">
               <div class="col left">
                  <h3 class="entry-title"><?php echo $textotitulocat; ?> </h3>
               </div>
            </div>
               <div class="<?php echo  $nome_carrosel; ?>">
            
                        <?php
                              $contador= 0;
                              foreach($users_anunciantes_carrosel as $dadosAnunciantes){ 

                              $contador++;
                              ?>
                              <div class="">
                              
                              <?php
                              if(trim($dadosAnunciantes->foto_do_anunciante)=='' or $dadosAnunciantes->foto_do_anunciante=='00000000-0000-0000-0000-000000000000'){
                                 $dadosAnunciantes->foto_do_anunciante = 'https://2.gravatar.com/avatar/ec65a0d5f2c7d6732407df4c552409c9?s=64&d=mm&r=g';
                              }else{
            
                                    /* $file = 'https://acharefacil.blob.core.windows.net/publico/foto/'.strtolower($dadosAnunciantes->foto_do_anunciante).'.jpeg';
                                    $file_headers = @get_headers($file);
                        
                                    if (!strripos($file_headers[0], '404')) {
                                       $dadosAnunciantes->foto_do_anunciante = $file;
                                    
                                    }else {
                                    */
                                       $upload_url = wp_upload_dir();
                                       $upload_url = $upload_url['baseurl'] . '/addify_registration_uploads/';

                                       $caminho = '/wp-content/uploads/addify_registration_uploads/'.$dadosAnunciantes->foto_do_anunciante;


                                    // $file_headers = get_headers($upload_url.$dadosAnunciantes->foto_do_anunciante);
                                       //echo $upload_url.$dadosAnunciantes->foto_do_anunciante;
                                       //echo  $dadosAnunciantes->foto_do_anunciante = $upload_url.strtolower($dadosAnunciantes->foto_do_anunciante).'.jpeg';
                                       //exit;
                                       if(file_exists($caminho)){ 
                                          $dadosAnunciantes->foto_do_anunciante = '/'.$caminho;
                                       }else if(file_exists($caminho.'.jpeg')){
                                          $dadosAnunciantes->foto_do_anunciante ='/'.$caminho.'.jpeg';
                                       }else{
                                          $dadosAnunciantes->foto_do_anunciante = 'https://2.gravatar.com/avatar/ec65a0d5f2c7d6732407df4c552409c9?s=64&d=mm&r=g';
         
                                       }
                                    
                                    // }
                                 }

                           
                              
                           
                              
                           
                           ?>


                     

                        
                           <div  aria-hidden="false"style="width: 236px;">
                              <div class="product type-product post-2887 status-publish first instock product_cat-auto-escola product_cat-automotivo product_cat-toys-video-games product_cat-cosmeticos product_cat-eletronicos product_cat-imobiliarias product_cat-lavanderias product_cat-moda-accessorios product_cat-sorveterias has-post-thumbnail shipping-taxable product-type-simple">
                                 <div class="product-wrapper with-content-fade product-type-1 quadro_anuncio_recente_home">
                                    <div class="product-inner">
                                       <div class="product-thumbnail-wrapper">
                                       
                                          <!-- product-buttons -->
                                          <div class="product-thumbnail thumbnail-gallery-dots-style-1 thumbnail-gallery-hover">
                                             <a href="/detalhe?detalhe_anunciante=<?php echo $dadosAnunciantes->ID; ?>" tabindex="0">
                                                <img fetchpriority="high" decoding="async"   src="<?php echo $dadosAnunciantes->foto_do_anunciante; ?>" class="imagem_carrosel_anunciantes" ></a></div>
                                          <!-- product-thumbnail -->
                                       </div>
                                       <!-- product-thumbnail-wrapper -->
                                       <div class="product-content-wrapper">
                                          <div class="product-content-body">
                                             <div class="product-content-row">
                                                <div class="product-price-wrapper"><span class="price"></span></div>
                                                <!-- product-price-wrapper -->
                                                <h2 class="product-title">
                                                   <a href="/detalhe?detalhe_anunciante=<?php echo $dadosAnunciantes->ID; ?>" 
                                                   tabindex="0"><span><?php echo substr(ucfirst($dadosAnunciantes->nome_do_seu_negocio),0,100); ?>
                                                   </span><br><br></a></h2>
                                             </div>
                                             <!-- product-content-row -->
                                          </div>
                                          <!-- product-content-body -->
                                          <div class="product-content-footer descricao_carrosel_anunciante">
                                             <?php echo substr($dadosAnunciantes->descricao,0,50).' ...'; ?>
                                          </div>

                                       </div>
                                       <!-- product-content-wrapper -->
                                    </div>
                                    <!-- product-inner -->
                                    <div class="product-hidden-content"></div>
                                    <!-- product-hidden-content -->
                                 </div>
                                 <!-- product-wrapper -->
                                 <div class="product-content-fade style-1" style="margin-bottom: -16px;"></div>
                              </div>
                           </div>
                           </div>
                           <?php }  ?>
                        
                        
                     
                     </div>
            
</div>
            </div>
         </div>
      </div>
   </div>
</div>